[package]
name = "peasant"
description = "harvest message collector and granary log message store"
license = "MIT"
repository = "https://github.com/patrickbucher/peasant"
version = "0.0.1"
edition = "2021"

[dependencies]
